### ISSUE TITLE
Нужен релиз программы

### ISSUE THREAD

**Issue by bonvech** [omixyy/Devil-s-Massacre#1]
Сделайте исполняемый файл, который можно скачать и играть без установки питона и его библиотек.

**Comment by omixyy** [comment]
Сделал релиз

**Comment by bonvech** [comment]
Релиз должен быть виден на первой странице репозитория и в релизах:
https://github.com/omixyy/Devil-s-Massacre/releases

На гитхабе есть специальный механизм публикации релизов.

**Comment by omixyy** [comment]
Посмотрите сейчас. Вроде сделал

вс, 21 янв. 2024 г., 11:04 bonvech ***@***.***>:

**Comment by bonvech** [comment]
Там же в релизе должен быть и экзешник. Если будет новая версия - то новый релиз.

**Comment by omixyy** [comment]
А exe есть

вс, 21 янв. 2024 г., 15:04 bonvech ***@***.***>:

**Comment by bonvech** [comment]
При переходе на вкладку релизов там должен быть доступен экзешник. Т.е. в каждом релизе будет свой экзешник. Прямо в релизе, а не в репозитории. В репозитории его как раз не должно быть.

Например, у меня так:
https://github.com/bonvech/Aethalometer/releases/tag/AE43

**Comment by omixyy** [comment]
Ну, насколько я вижу, у Вас так же, как у меня: скачивается архив со всеми
нужными файлами, в том числе с .exe. Я запутался

вс, 21 янв. 2024 г., 15:37 bonvech ***@***.***>:

**Comment by bonvech** [comment]
У тебя в релизе только архивы с исходным кодом программы. А должен быть еще отдельно сам экзешник или архив с папкой с экзешником и всеми файлами, необходимыми для корректной работы (например, картинки или конфигурационные файлы).
Архив распаковывается и сразу можно запустить программу.

Тот, кому не интересен твой код, должен иметь возможность скачать из релиза только исполняемую часть.

Файл ехе из репозитория нужно удалить. Оставить его только в релизе.

**Comment by omixyy** [comment]
Во, сделал. Посмотрите, сейчас вроде всё как надо

вс, 21 янв. 2024 г. в 16:04, bonvech ***@***.***>:

**Comment by bonvech** [comment]
У тебя в релизе два архива. Оба имеют имя Source code(zip) - исходный код. В них должен быть только код, никаких бинарников.
Файл архива с исполняемым бинарником (со всеми необходимыми файлами для запуска программы) должен быть загружен вручную с компьютера.

https://docs.github.com/ru/repositories/releasing-projects-on-github/managing-releases-in-a-repository
Обрати внимание на пункт 9. 

В товоем релизе должно быть два файла исходников в двух форматах архива и архив с бинарником. Итого ТРИ файла.

**Comment by omixyy** [comment]
Ну вроде сделал

вс, 21 янв. 2024 г. в 18:00, bonvech ***@***.***>:

**Comment by bonvech** [comment]
Поздравляю с первым релизом!
